### ISSUE TITLE
Support Async Version in .NET 4.0 With Microsoft.Bcl.Async

### ISSUE THREAD

**Issue by vector-man** [brandondahler/Data.HashFunction#15]
Would it be possible to add support for the async version of the library in .NET 4.0, using Microsoft.Bcl.Async? I'm going to try to do it myself, but it would be nice if there was a Nuget package available for that.

**Comment by brandondahler** [comment]
Sounds simple enough, I'll take a look at it.

**Comment by brandondahler** [comment]
There are now *.Net40Async versions of all the packages that will allow net40 applications to use the async/await functionality.
