### ISSUE TITLE
How to get hash code

### ISSUE THREAD

**Issue by nehmebilal** [brandondahler/Data.HashFunction#19]
Hi,

I am trying to use your library to get the hash code of a given string. I'd like to use the hash code for load balancing and I'm looking for a consistent hash code (for a given string, I always get the same hash code).

Here is what it looks like:

```csharp
int nodeIndex = GetHashCode(sessionId) % nodeCount;
Nodes[nodeIndex].DoWork();
```

Does this library provide such functionality?

**Comment by kentkost** [comment]
You will always get the same hashcode for the same string your're trying to hash.
xxhash is a Non-cryptographic hash method.

Hope that answers your question.

**Comment by nehmebilal** [comment]
Perfect thanks!
