### ISSUE TITLE
xxHash - Horrible constructor overload

### ISSUE THREAD

**Issue by brandondahler** [brandondahler/Data.HashFunction#22]
From https://stackoverflow.com/questions/30911887/xxhash-convert-resulting-in-hash-too-long .

Data.HashFunction/src/xxHash/xxHash.cs:96 - There are two overloads of the constructor, one with int and one with ulong.  This is bad for obvious reasons.

**Comment by kentkost** [comment]
Wouldn't it be better just to have a single constructor with no arguments - and just have the default be 64bit? Since xxHash performs worse at 32bit and so far to users has already made the mistake of not being able to convert the 32bit hash into a ulong, because the default value is 32bit.

**Comment by brandondahler** [comment]
I have verified that this has been resolved in v2.0.
