### ISSUE TITLE
Support an overload with stream

### ISSUE THREAD

**Issue by fleed** [brandondahler/Data.HashFunction#23]
Is it possible to support an overload that accepts a Stream, for bigger files?

**Comment by DoCode** [comment]
What about this?

**Comment by brandondahler** [comment]
What about it? IHashFunction and IHashFunctionAsync has ComputeHash functions that take a byte array or a Stream.

**Comment by DoCode** [comment]
Ah sorry. What I mean, what I need, is block precessing like all .NET hash algorythm provide.

**Comment by brandondahler** [comment]
Can open a new issue with some basic pseudo code you’d like to see and the overall goal you’re trying to achieve?

**Comment by DoCode** [comment]
@brandondahler thanks. I created a new issue: #37
