### ISSUE TITLE
.NET core support

### ISSUE THREAD

**Issue by wowsuchdeveloper** [brandondahler/Data.HashFunction#24]
Could you please add .NET core support to your nuget package?

**Comment by brandondahler** [comment]
I am not particularly acquainted with what is required to make it .net core compatible. If you can provide me with some details or a pull request with the changes, I'd be happy to get the packages updated. 

Brandon

**Comment by brandondahler** [comment]
I've started working on upgrading the project to .NET core in general.  This is a non-negligible change so it might be a while until you see an release for it.

**Comment by brandondahler** [comment]
@wowsuchdeveloper There is now a pre-release version avaliable on NuGet, this was build from the current DotNetCore branch.  I plan on doing a bit more testing and modification of documentation before merging this to master and officially deploying 2.x .

**Comment by DixonDs** [comment]
Hi @brandondahler ! Is stable 2.0 going to be released anytime soon?

**Comment by brandondahler** [comment]
I'm still contemplating some (possibly breaking) API changes since I'll be releasing a new major version.  I'll review where I'm at today or tomorrow and see if I can give you a better answer.

**Comment by j2ghz** [comment]
I'm also interested in the .NET Core version. Any news?

**Comment by brandondahler** [comment]
I have made an update with the latest API changes that will be a part of the 2.0 release.  There is now an updated -ci-27 prerelease version of each package available.

There are still two things left to do before 2.0 can be released:
1. Clean up all warnings generated from the documentation
2. Finish creating/updating tests for the new APIs.

I would expect we're still probably between a week and a month out.

**Comment by stankovski** [comment]
Any updates on 2.0 stable?

**Comment by brandondahler** [comment]
v2.0 is officially stable.  

Sorry for the utter lack of timeline management and constant missed promises.
