### ISSUE TITLE
Release new preview packages

### ISSUE THREAD

**Issue by NickDarvey** [brandondahler/Data.HashFunction#33]
Hi,

I was wondering if it was possible to release a new set of preview packages?
The latest packages, v2.0.0-ci-00027, are missing a lot of work you've done, e.g. [making `JenkinsLookup3Factory.Instance` static](https://github.com/brandondahler/Data.HashFunction/commit/eca002e6652b79e7a8cff49d5ae530885ce8e226#diff-081126045eb5b911bf4546814e6bb998).

Thanks,
Nick

**Comment by brandondahler** [comment]
Released v2.0.0-ci-00033

**Comment by NickDarvey** [comment]
Thank you!
