### ISSUE TITLE
Example in README is wrong signature

### ISSUE THREAD

**Issue by joshnoe** [brandondahler/Data.HashFunction#42]
In the README code example, `ComputeHash` accepts a string:

`var hashValue = _jenkinsOneAtATime.ComputeHash("foobar");`

...however, `ComputeHash` actually accepts a byte array.

Let me know and I'll gladly create a pull request.

**Comment by brandondahler** [comment]
System.Data.HashFunction.Core contains extension functions for IHashFunction including the one below as syntactic sugar on top of the ones defined in the interface.

```
        public static IHashValue ComputeHash(this IHashFunction hashFunction, string data)
        {
            return hashFunction.ComputeHash(
                Encoding.UTF8.GetBytes(data));
        }
```
